deployments:
  pipelines:
    dockerimage: ubuntu:trusty
    pipelines:
      - website:
          dockerimage: ubuntu:xenial
          build_steps:
            - apt-get update && apt-get install -y git curl
          scripts:
            - echo "true"
            - ls -la
