deployments:
  app:
    dockerimage: ubuntu:trusty
    pipelines:
      - test:
          depends_on_group: qwe
          group_id: cde
          dockerimage: python:latest
          build_steps:
            - apt-get update && apt-get install -y git curl         
          scripts:
            - echo true
      - test-no-longer-failing-smth-long-long-long-to-be-truncated:
          dockerimage: nginx:latest
          scripts:
            - false
            - echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
      - smth:
          group_id: qwe
          depends_on_group: abc
          dockerimage: nginx:latest
          build_steps:
            - apt-get update && apt-get install -y curl
          scripts:
            - echo true
            - sleep 20
      - a2:
          group_id: abc
          depends_on_group: bbb
          dockerimage: nginx:latest
          build_steps:
            - apt-get update && apt-get install -y curl
          scripts:
            - echo true
            - sleep 20
      - a3:
          group_id: abc
          depends_on_group: bbb
          dockerimage: nginx:latest
          build_steps:
            - apt-get update && apt-get install -y curl
          scripts:
            - echo true
            - sleep 20
      - circular:
          group_id: qwe
          dockerimage: nginx:latest
          build_steps:
            - apt-get update && apt-get install -y curl
          scripts:
            - echo true
            - sleep 20
      - test-not-parsed-without-scripts:
          dockerimage: odoo:latest
          depends_on_group: cde
          group_id: bbb
          scripts:
            - echo true
            - sleep 20
