deployments:
  nodocker:
    dockerimage: nginx
    squash-cmd--aws-credentials:
      aws_access_key: $ACCESS_KEY
      aws_secret_key: $SECRET_KEY
      region: us-east-2
    pipelines:
      - s3:
          scripts:
            - mkdir user-pics
            - touch user-pics/filename2
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                from_folder: user-pics
                action: download
                arguments: |
                 --quiet  \
                 --cache-control "max-age=11300"
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                from_folder: user-pics
                to_folder: test-upload
                arguments: |
                 --quiet  \
                 --cache-control "max-age=11300"

