deployments:
  app:
    dockerimage: ubuntu:trusty
    pipelines:
      - test with spaces very longish here:
          depends_on_group: abc
          group_id: cde
          dockerimage: python:latest
          build_steps:
            - apt-get update && apt-get install -y git curl         
          scripts:
            - echo true
      - smth:
          group_id: abc
          dockerimage: nginx:latest
          build_steps:
            - apt-get update && apt-get install -y curl
          scripts:
            - echo true
      - test-not-parsed-without-scripts:
          dockerimage: odoo:latest
          depends_on_group: abc
          group_id: cde
      - test-no-longer-failing-smth-long-long-long-to-be-truncated:
          dockerimage: nginx:latest
          scripts:
            - sleep 60 && echo success
  
