deployments:
  pipelines:
    dockerimage: nginx:latest
    build_policy:
      triggers: pr
    pipelines:
      - website:
          dockerimage: ubuntu:xenial
          build_steps:
            - apt-get update && apt-get install -y git curl
          scripts:
            - ls -la
