deployments:
  nodocker:
    dockerimage: nginx
    squash-cmd--aws-credentials:
      aws_access_key: $ACCESS_KEY
      aws_secret_key: $SECRET_KEY
      region: us-east-2
    pipelines:
      - s3:
          build_steps:
            - echo
            - mkdir /cp
            - cd /code
          scripts:
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                from_folder: mysite/*
                to_folder: /
                files_only: true
                arguments: |
                 --quiet  \
                 --cache-control "max-age=11300"          
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                from_folder: /code/*
                to_folder: /test-upload/
                files_only: true
                arguments: |
                 --quiet
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                from_folder: /code/*
                to_folder: /test-uploads
                arguments: |
                 --quiet
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                action: download
                from_folder: /user-pics/*
                to_folder: /code/
                arguments: --quiet
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                action: download
                from_folder: /user-pics/sub/*
                to_folder: /cp
                arguments: --quiet
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                action: download
                from_folder: /user-pics
                to_folder: /cp
                arguments: --quiet                 
            - ls -la /code/
            - ls -la /cp
