deployments:
  default:
    dockerimage: ubuntu:18.04
    build_steps:
      - >
        DEBIAN_FRONTEND=noninteractive apt-get update &&
        DEBIAN_FRONTEND=noninteractive apt-get install -y
        software-properties-common
        sudo supervisor ssh git curl locales
        gcc build-essential
        libfontconfig1 libfontconfig1-dev libssl-dev libpq-dev
        python3.6 python3.6-dev python3.6-venv python3-pip
      - WORKDIR /code
      - 'echo "PWD IN BUILD STEPS: $PWD"'
      - python3 -m venv venv
      - ls -la
    post_build_steps:
      - ls -la
      - python3 -m venv venv
      - ls -la /code/venv
    launch_steps:
      - cd /code
      - ls -la
