deployments:
  nodocker:
    dockerimage: nginx
    squash-cmd--aws-credentials:
      aws_access_key: $ACCESS_KEY
      aws_secret_key: $SECRET_KEY
      region: us-east-2
    build_steps:
      - apt-get update
    pipelines:
      - Tests:
          group_id: tests
          scripts:
            - cd /code
            - ls -la
            - sleep 20
            - false
      - Core Tests:
          group_id: core
          scripts:
            - sleep 5
            - abc
      - Production:
          depends_on_group: tests
          scripts:
            - echo true
