deployments:
  pipelines:
    build_policy:
      allow_branches: "*"
    auto_deploy_on_commits: true
    dockerimage: ubuntu:trusty
    pipelines:
      - website:
          build_policy:
            triggers: 
              - pr
          dockerimage: ubuntu:xenial
          build_steps:
            - apt-get update && apt-get install -y git curl
          scripts:
            - echo true
  app:
    dockerimage: nginx
    auto_deploy_on_commits: true
    build_policy:
      restrict_branches: config, build_policy_pr
      triggers: 
        - commit
    pipelines:
      - website:
          scripts:
            - ls -la
      - test:
          dockerimage: ubuntu:latest
          build_steps:
            - which apt-get
          scripts:
            - true
