deployments:
  pipelines:
    dockerimage: ubuntu:trusty
    build_policy:
      restrict_branches: branch
    pipelines:
      - website:
          dockerimage: ubuntu:xenial
          build_steps:
            - apt-get update && apt-get install -y git curl
            - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --allow-unauthenticated postgresql postgresql-contrib libpq-dev pgadmin3
            - cd /code/mysite/
            - service postgresql start && su postgres bash -c "psql -c 'create database test_db;'"
            - service postgresql start && su postgres bash -c "psql -c "\""alter user postgres with password 'postgres';"\"""
            - apt-get install -y software-properties-common python-software-properties
            - add-apt-repository ppa:deadsnakes/ppa -y
            - apt-get update && apt-get install -y python3.6 python-setuptools python3.6-dev
            - curl https://bootstrap.pypa.io/get-pip.py | python3.6
            - pip3 install --upgrade setuptools
            - pip3 install -r ./requirements.txt
          scripts:
            - service postgresql start
            - cd /code/mysite && POSTGRES_HOST=localhost POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres POSTGRES_DB=test_db coverage run ./manage.py test --verbosity 2 && coverage report --fail-under=30
