deployments:
  nodocker:
    dockerimage: nginx
    squash-cmd--aws-credentials:
      aws_access_key: $ACCESS_KEY
      aws_secret_key: $SECRET_KEY
      region: us-east-2
    pipelines:
      - primary:
          group_id: api
          scripts:
            - echo true
      - next:
          group_id: api
          scripts:
            - sleep 11; ls -la
      - dependency:
          group_id: app
          depends_on_group: api
          scripts:
            - ls -la
